#!/usr/bin/env sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "^backend/.*\.java$" || true)

# Se não houver arquivos Java staged, sai com sucesso
[ -z "$STAGED_FILES" ] && exit 0

echo "Houveram mudanças em arquivos Java. Rodando Spotless..."

cd backend || exit 1

./mvnw spotless:apply || exit 1

cd .. || exit 1

# Re-adiciona SOMENTE os arquivos que estavam staged
echo "$STAGED_FILES" | xargs git add
exit 0